FROM alpine

# Metadata
LABEL org.opencontainers.image.title="abhisheksr01/alpine" \
      org.opencontainers.image.url="https://hub.docker.com/repository/docker/abhisheksr01/alpine"

RUN apk update && apk add curl jq bash